#!/bin/bash

# SOURCE_FOR_UNIT_TESTING=1
# source ./filename

plan=2

function pass() { plan=$(($plan - 1)); }
function fail() { echo fail at "$@"; exit 1 ; }
function assert() { test $? -eq 0 && pass || fail $(caller) "$@" ; }
function refute() { test $? -ne 0 && pass || fail $(caller) "$@" ; }

# three equals three, and not four
t() {
  test 3 -eq 3 ; assert
  test 4 -eq 3 ; refute
};t

test $plan -eq 0 && pass || fail  "expected $plan more passing tests"
echo 'success'
